Add tutorial 1 of riotjs
hackatory/hackatory.github.io pull request #12
Opened 2017-07-16 17:35 UTC by lucasroman

2017-07-18 23:44 UTC, olvap commented
@lucasroman te agregué unos detalles y arreglé el largo de algunas lineas. decime que te parece. Por mi ya lo podemos mergear y ver de armar el segundo tutorial.

2017-07-21 16:53 UTC, eloyesp requested changes
El tutorial tiene algunos problemas que ahí te marqué... además hice un plunker donde se puede probar, para asegurar que ande: http://plnkr.co/edit/8PPUPoovZy27RYj00uwU?p=preview

2017-07-21 16:53 UTC, eloyesp commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +Notar que las etiquetas del componente ```<hello-world/>``` que definimos se
Esto es cierto sólo en los archivos .tag, no en html.

2017-07-21 16:53 UTC, eloyesp commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +    name = opts.name
esto sería `this.name = opts.name || "mundo"` de esta forma es más simple el montaje del elemento (y es más fácil de utilizar).

2017-07-21 16:53 UTC, eloyesp commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +  <h1>hola {name}!</h1>
No sería mejor usar `{opts.name}` directamente?

2017-07-21 16:53 UTC, eloyesp commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +  </script>
Este script va al final del documento o esperar al evento `onready`. En este caso está andando solo porque tarda en compilar el tag.

2017-07-21 16:53 UTC, eloyesp commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +categories: en
El texto está en español, así que la category sería "es".

2017-07-21 16:53 UTC, eloyesp commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +  </style>
Sería mejor utilizar [scoped css](http://riotjs.com/guide/#tag-styling).

2017-07-21 17:23 UTC, olvap commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +    name = opts.name
@lucasroman querés agregar un comentario porque usamos el default en el momentod de montar el componente.

2017-07-21 17:24 UTC, olvap commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +  <h1>hola {name}!</h1>
La idea era mostrar que la lógica va en otro lado. a lo mejor podamos hacer algo más complejo.

2017-07-21 17:25 UTC, olvap commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +  </style>
ni

2017-07-22 21:34 UTC, lucasroman commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +  </style>
Preferiría no incorporar demasiados conceptos nuevos al principio para no complicar a la persona que lo lea, recuerden que sería una de las primeras cosas hechas en riot. Pero si lo consideran útil lo agrego.

2017-07-22 21:46 UTC, lucasroman commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +  <h1>hola {name}!</h1>
@eloyesp la respuesta a tu pregunta es "sí", pero fijate que arriba de ese código hay una lista de elementos que puede tener un tag:
- CSS
- HTML
- Javascript

La idea de ese código es mostrar una correspondencia con esa lista para que se vean claramente esas tres secciones.

2017-07-22 22:12 UTC, lucasroman commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +    name = opts.name
Bueno acá hay dos cosas para aclarar:
1. El "this" lo estuvimos discutiendo con @olvap si iba o no. Yo lo borré porque en la guía de riot decía:

> Smart ES6 like method syntax is supported: methodName() { } becomes this.methodName = function() {}.bind(this) where this always points to the current tag instance.

Pero puede que lo haya entendido mal y se refería a cuando estás **usando** del tag en el HTML, no en el archivo .tag. Bueno, si está mal me avisan y lo vuelvo a poner.

2.  Es cierto @eloyesp. Lo hicimos así porque @olvap me enseñó que se pueden pasar atributos al componente en el momento de montarlo. La idea sería mostrar ese concepto.

2017-07-22 22:20 UTC, lucasroman commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +  </script>
I agree. Will be in next commit.

2017-07-22 22:46 UTC, lucasroman commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +Notar que las etiquetas del componente ```<hello-world/>``` que definimos se
No entiendo bien a qué te referís. Querés decir que los saludos personalizados y por defecto sólo funcionan porque <hello-world> es una etiqueta personalizada, en cambio en las etiquetas nativas de HTML no pueden hacer eso. ¿Eso querés decir?.

2017-07-22 23:12 UTC, lucasroman commented
Lo de Plunker lo estuve viendo y al igual que [jsfiddle](https://jsfiddle.net/) parece que tienen problemas con las self-closing tags. En mi navegador funciona bien pero por las dudas les paso los archivos por mail (por acá no me deja) para que lo prueben.

Fuente: https://stackoverflow.com/questions/39380207/why-does-only-one-of-my-riot-js-tags-render/39391178#39391178

2017-08-01 13:36 UTC, eloyesp commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +  </style>
ok

2017-08-01 13:39 UTC, eloyesp commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +  <h1>hola {name}!</h1>
En ese caso, lo mejor sería agregar algo de javascript real, una posibilidad sería agregar los signos de admiración pasados 5 segundos o algo así:

```javascript
setTimeout(function () { "agregar el signo de admiración o hacer algo loco" }, 1000)
```

2017-08-01 13:57 UTC, eloyesp commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +  </style>
Al parecer está bien así....

2017-08-01 15:13 UTC, olvap commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +  <script type=riot/tag src="hello-world.tag"></script>
en los pasos de arriba, estás poniendo que los scripts los vas agregando en el head, pero cuando los mostrás terminado, están en e body.

2017-08-22 12:15 UTC, eloyesp requested changes

2017-08-22 12:15 UTC, eloyesp commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +</head>
En el texto dice: <q>al final del `body`</q> pero en el ejemplo está en el `head`...

2017-08-23 13:34 UTC, lucasroman commented on _posts/2017-07-14-tutorial1-ritotjs-basic-component.md
> +  <h1>hola {name}!</h1>
No me olvidé de ésto pero quiero hacerlo usando TDD. Estoy viendo QUnit ahora, cuando aprenda lo suficiente subo el código.

2017-09-07 14:16 UTC, eloyesp approved these changes

2017-09-28 18:12 UTC, merged