Is not a Mass
hackatory/hackatory.github.io pull request #5
Opened 2016-12-30 14:38 UTC by julioalucero

@eloyesp @olvap @antico5 @noili @hsulionel 

Si al menos alguno le podría pegar una mirada se lo agradezo, gracias totales

2016-12-30 15:13 UTC, eloyesp requested changes
I like it, but I think it could be improved.

2016-12-30 15:13 UTC, eloyesp commented on _posts/2016-12-30-Is-not-a-Mass-is-just-a-stand-up.markdown
> +title:  "Is not a Mass, is just a stand-up"
"Mass" is not clear enough, may be use the word *rite* or *sacrament*.

2016-12-30 15:13 UTC, eloyesp commented on _posts/2016-12-30-Is-not-a-Mass-is-just-a-stand-up.markdown
> +Each day, at 12.00 am, the priest is ready to start the mass. It doesn’t really matter what you did or not the last day or even the quality of the code, the only most important thing is that you be t
The word priest is very catholic, may be pastor, lord or minister could work better.

2016-12-30 15:13 UTC, eloyesp commented on _posts/2016-12-30-Is-not-a-Mass-is-just-a-stand-up.markdown
> +> “Please inform with at least 34.3 hours before if you can’t assist a
36 sounds better.

2016-12-30 15:13 UTC, eloyesp commented on _posts/2016-12-30-Is-not-a-Mass-is-just-a-stand-up.markdown
> +Not to be strict in this kind of thinks helps to generate a good atmosphere in the project, which in consequence helps to keep you motivated and this last adjective believe me that is something that
Could you refrase "Not to be strict" with something positive, like "being flexible"?

2016-12-30 15:15 UTC, julioalucero commented on _posts/2016-12-30-Is-not-a-Mass-is-just-a-stand-up.markdown
> +title:  "Is not a Mass, is just a stand-up"
Let's go with Sacrament

2016-12-30 15:15 UTC, julioalucero commented on _posts/2016-12-30-Is-not-a-Mass-is-just-a-stand-up.markdown
> +Each day, at 12.00 am, the priest is ready to start the mass. It doesn’t really matter what you did or not the last day or even the quality of the code, the only most important thing is that you be t
Pastor

2016-12-30 15:17 UTC, julioalucero commented on _posts/2016-12-30-Is-not-a-Mass-is-just-a-stand-up.markdown
> +Not to be strict in this kind of thinks helps to generate a good atmosphere in the project, which in consequence helps to keep you motivated and this last adjective believe me that is something that
cool, yes. I have to learn to not say non negative things. I said it even in a interviews

2016-12-31 15:43 UTC, olvap commented on _posts/2016-12-30-Is-not-a-Sacrament-is-just-a-stand-up.markdown
> +Being flexible about meetings helps to generate a good atmosphere in the project, which in consequence helps to keep you motivated and this last adjective believe me that is something that the client
que te parece cambiar este ultimo parrafo por:

Being flexible about meetings helps to generate a good atmosphere in the project, which in consequence help you to keep motivated and this, believe me, is something that the client is interested in.

2017-01-02 18:43 UTC, antico5 commented on _posts/2016-12-30-Is-not-a-Sacrament-is-just-a-stand-up.markdown
> +Bosses, PMs, whatever has to re-organize his priority, there are at least 36 different most important things in a project than this meeting. 
Algunas correcciones:
..the only most important thing is that you **are** there..
Bosses, PMs, **whateever**, **have** to re-organize..
..there are at least 36 different **more** important things..

Muy bueno

2017-01-08 15:37 UTC, julioalucero commented on _posts/2016-12-30-Is-not-a-Sacrament-is-just-a-stand-up.markdown
> +Bosses, PMs, whatever has to re-organize his priority, there are at least 36 different most important things in a project than this meeting. 
thanks

2017-01-08 15:38 UTC, julioalucero commented on _posts/2016-12-30-Is-not-a-Sacrament-is-just-a-stand-up.markdown
> +Being flexible about meetings helps to generate a good atmosphere in the project, which in consequence helps to keep you motivated and this last adjective believe me that is something that the client
thanks

2017-01-13 13:27 UTC, merged